# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 84da188f851182f7c59410430873193876dad109b5a7f2ce29c79e6a8cc5f523b86270721592825a4aa611c35a829cc4c61460d7d9dcf74713a40bf2548abd0f

test:
  secret_key_base: bdfeaaf2f290c5a0185e8c6db2406be9598860bbd7aea681b80b317540865e78e96236b9bc36b4648b5c5a8549f323fd02597abddbe6f943e81d73e5961e969c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
